<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net11.0</TargetFramework>
    <RootNamespace>ElliePdf.Rendering</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ElliePdf.Domain\ElliePdf.Domain.csproj" />
    <ProjectReference Include="..\ElliePdf.Pdf.Contracts\ElliePdf.Pdf.Contracts.csproj" />
  </ItemGroup>
</Project>
